In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
independent=dataset[[ 'Age', 'EstimatedSalary','Gender_Male']]

In [10]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000         True
1     35            20000         True
2     26            43000        False
3     27            57000        False
4     19            76000         True
..   ...              ...          ...
395   46            41000        False
396   51            23000         True
397   50            20000        False
398   36            33000         True
399   49            36000        False

[400 rows x 3 columns]

In [11]:
dependent=dataset[['Purchased']]

In [12]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
from sklearn.model_selection import GridSearchCV
param_grid= {'algorithm':['auto','kd_tree','brute'],
             'n_neighbors':[5,10,50,100]}
grid=GridSearchCV(KNeighborsClassifier(),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted') 
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END .....algorithm=auto, n_neighbors=5;, score=0.867 total time=   0.0s
[CV 2/5] END .....algorithm=auto, n_neighbors=5;, score=0.906 total time=   0.0s
[CV 3/5] END .....algorithm=auto, n_neighbors=5;, score=0.870 total time=   0.0s
[CV 4/5] END .....algorithm=auto, n_neighbors=5;, score=0.944 total time=   0.0s
[CV 5/5] END .....algorithm=auto, n_neighbors=5;, score=0.981 total time=   0.0s
[CV 1/5] END ....algorithm=auto, n_neighbors=10;, score=0.847 total time=   0.0s
[CV 2/5] END ....algorithm=auto, n_neighbors=10;, score=0.887 total time=   0.0s
[CV 3/5] END ....algorithm=auto, n_neighbors=10;, score=0.849 total time=   0.0s
[CV 4/5] END ....algorithm=auto, n_neighbors=10;, score=0.944 total time=   0.0s
[CV 5/5] END ....algorithm=auto, n_neighbors=10;, score=0.962 total time=   0.0s
[CV 1/5] END ....algorithm=auto, n_neighbors=50;, score=0.716 total time=   0.0s
[CV 2/5] END ....algorithm=auto, n_neighbors=50;, score=0.702 total time=   0.0s
[CV 3/5] END ....algorithm=auto, n_neighbors=50;, score=0.557 total time=   0.0s
[CV 4/5] END ....algorithm=auto, n_neighbors=50;, score=0.796 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

[CV 5/5] END ....algorithm=auto, n_neighbors=50;, score=0.711 total time=   0.0s
[CV 1/5] END ...algorithm=auto, n_neighbors=100;, score=0.687 total time=   0.0s
[CV 2/5] END ...algorithm=auto, n_neighbors=100;, score=0.734 total time=   0.0s
[CV 3/5] END ...algorithm=auto, n_neighbors=100;, score=0.483 total time=   0.0s
[CV 4/5] END ...algorithm=auto, n_neighbors=100;, score=0.666 total time=   0.0s
[CV 5/5] END ...algorithm=auto, n_neighbors=100;, score=0.617 total time=   0.0s
[CV 1/5] END ..algorithm=kd_tree, n_neighbors=5;, score=0.867 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

[CV 2/5] END ..algorithm=kd_tree, n_neighbors=5;, score=0.906 total time=   0.0s
[CV 3/5] END ..algorithm=kd_tree, n_neighbors=5;, score=0.870 total time=   0.0s
[CV 4/5] END ..algorithm=kd_tree, n_neighbors=5;, score=0.944 total time=   0.0s
[CV 5/5] END ..algorithm=kd_tree, n_neighbors=5;, score=0.981 total time=   0.0s
[CV 1/5] END .algorithm=kd_tree, n_neighbors=10;, score=0.847 total time=   0.0s
[CV 2/5] END .algorithm=kd_tree, n_neighbors=10;, score=0.887 total time=   0.0s
[CV 3/5] END .algorithm=kd_tree, n_neighbors=10;, score=0.849 total time=   0.0s
[CV 4/5] END .algorithm=kd_tree, n_neighbors=10;, score=0.944 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

[CV 5/5] END .algorithm=kd_tree, n_neighbors=10;, score=0.962 total time=   0.0s
[CV 1/5] END .algorithm=kd_tree, n_neighbors=50;, score=0.716 total time=   0.0s
[CV 2/5] END .algorithm=kd_tree, n_neighbors=50;, score=0.702 total time=   0.0s
[CV 3/5] END .algorithm=kd_tree, n_neighbors=50;, score=0.557 total time=   0.0s
[CV 4/5] END .algorithm=kd_tree, n_neighbors=50;, score=0.796 total time=   0.0s
[CV 5/5] END .algorithm=kd_tree, n_neighbors=50;, score=0.711 total time=   0.0s
[CV 1/5] END algorithm=kd_tree, n_neighbors=100;, score=0.687 total time=   0.0s
[CV 2/5] END algorithm=kd_tree, n_neighbors=100;, score=0.734 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

[CV 3/5] END algorithm=kd_tree, n_neighbors=100;, score=0.483 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, n_neighbors=100;, score=0.666 total time=   0.0s
[CV 5/5] END algorithm=kd_tree, n_neighbors=100;, score=0.617 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

[CV 1/5] END ....algorithm=brute, n_neighbors=5;, score=0.867 total time=   0.2s
[CV 2/5] END ....algorithm=brute, n_neighbors=5;, score=0.906 total time=   0.0s
[CV 3/5] END ....algorithm=brute, n_neighbors=5;, score=0.870 total time=   0.0s
[CV 4/5] END ....algorithm=brute, n_neighbors=5;, score=0.944 total time=   0.0s
[CV 5/5] END ....algorithm=brute, n_neighbors=5;, score=0.981 total time=   0.0s
[CV 1/5] END ...algorithm=brute, n_neighbors=10;, score=0.847 total time=   0.0s
[CV 2/5] END ...algorithm=brute, n_neighbors=10;, score=0.887 total time=   0.0s
[CV 3/5] END ...algorithm=brute, n_neighbors=10;, score=0.849 total time=   0.0s
[CV 4/5] END ...algorithm=brute, n_neighbors=10;, score=0.944 total time=   0.0s
[CV 5/5] END ...algorithm=brute, n_neighbors=10;, score=0.962 total time=   0.0s
[CV 1/5] END ...algorithm=brute, n_neighbors=50;, score=0.716 total time=   0.0s
[CV 2/5] END ...algorithm=brute, n_neighbors=50;, score=0.702 total time=   0.0s
[CV 3/5] END ...algorithm=brute, n_neighbors=50;, score=0.557 total time=   0.0s
[CV 4/5] END ...algorithm=brute, n_neighbors=50;, score=0.796 total time=   0.0s
[CV 5/5] END ...algorithm=brute, n_neighbors=50;, score=0.711 total time=   0.0s
[CV 1/5] END ..algorithm=brute, n_neighbors=100;, score=0.687 total time=   0.0s
[CV 2/5] END ..algorithm=brute, n_neighbors=100;, score=0.734 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

[CV 3/5] END ..algorithm=brute, n_neighbors=100;, score=0.483 total time=   0.0s
[CV 4/5] END ..algorithm=brute, n_neighbors=100;, score=0.666 total time=   0.0s
[CV 5/5] END ..algorithm=brute, n_neighbors=100;, score=0.617 total time=   0.0s

C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=1,
             param_grid={'algorithm': ['auto', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 10, 50, 100]},
             scoring='f1_weighted', verbose=3)

In [37]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)

In [39]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [41]:
print(cm)

[[78  7]
 [ 4 45]]

In [43]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [45]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.93        85
           1       0.87      0.92      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.92      0.91       134
weighted avg       0.92      0.92      0.92       134

In [47]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'algorithm': 'auto', 'n_neighbors': 5}: 0.9183922682195829

In [49]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9411764705882354

In [51]:
table=pd.DataFrame.from_dict(re)

In [53]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003267,0.003352,0.009402,0.006106,auto,5,"{'algorithm': 'auto', 'n_neighbors': 5}",0.867478,0.906252,0.869709,0.944161,0.981233,0.913767,0.043854,1
1,0.000000,0.000000,0.012509,0.006254,auto,10,"{'algorithm': 'auto', 'n_neighbors': 10}",0.847141,0.886792,0.849057,0.944161,0.962264,0.897883,0.047683,4
2,0.004206,0.005847,0.013153,0.011768,auto,50,"{'algorithm': 'auto', 'n_neighbors': 50}",0.715520,0.701560,0.557004,0.796094,0.710627,0.696161,0.077414,7
3,0.003822,0.004783,0.030416,0.003446,auto,100,"{'algorithm': 'auto', 'n_neighbors': 100}",0.686728,0.733548,0.483019,0.666108,0.617087,0.637298,0.085730,10
4,0.004940,0.008011,0.025300,0.006206,kd_tree,5,"{'algorithm': 'kd_tree', 'n_neighbors': 5}",0.867478,0.906252,0.869709,0.944161,0.981233,0.913767,0.043854,1
5,0.000000,0.000000,0.029746,0.003019,kd_tree,10,"{'algorithm': 'kd_tree', 'n_neighbors': 10}",0.847141,0.886792,0.849057,0.944161,0.962264,0.897883,0.047683,4
6,0.000000,0.000000,0.027460,0.006068,kd_tree,50,"{'algorithm': 'kd_tree', 'n_neighbors': 50}",0.715520,0.701560,0.557004,0.796094,0.710627,0.696161,0.077414,7
7,0.005719,0.005051,0.025742,0.010021,kd_tree,100,"{'algorithm': 'kd_tree', 'n_neighbors': 100}",0.686728,0.733548,0.483019,0.666108,0.617087,0.637298,0.085730,10
8,0.003126,0.006252,0.065241,0.099223,brute,5,"{'algorithm': 'brute', 'n_neighbors': 5}",0.867478,0.906252,0.869709,0.944161,0.981233,0.913767,0.043854,1
9,0.000154,0.000307,0.010698,0.006390,brute,10,"{'algorithm': 'brute', 'n_neighbors': 10}",0.847141,0.886792,0.849057,0.944161,0.962264,0.897883,0.047683,4
10,0.003127,0.006254,0.007908,0.006601,brute,50,"{'algorithm': 'brute', 'n_neighbors': 50}",0.715520,0.701560,0.557004,0.796094,0.710627,0.696161,0.077414,7
11,0.000000,0.000000,0.015826,0.008527,brute,100,"{'algorithm': 'brute', 'n_neighbors': 100}",0.686728,0.733548,0.483019,0.666108,0.617087,0.637298,0.085730,10